// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';

//Sticky
export const GET_STICKY = 'GET_STICKY';
export const NOTES_UPDATE = 'NOTES_UPDATE';
export const FETCH_ALL_NOTES_SUCCESS = 'FETCH_ALL_NOTES_SUCCESS';
export const UPDATE_ALL_NOTES_SUCCESS = 'UPDATE_ALL_NOTES_SUCCESS';

//Contact
export const GET_All_CONTACT_SUCCESS = 'GET_All_CONTACT_SUCCESS';
export const ON_ADD_CONTACT_SUCCESS = 'ON_ADD_CONTACT_SUCCESS';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';

//inward module
export const FETCH_INWARD_LIST_REQUEST = 'FETCH_INWARD_LIST_REQUEST';
export const FETCH_INWARD_LIST_SUCCESS = 'FETCH_INWARD_LIST_SUCCESS';
export const FETCH_INWARD_LIST_ERROR = 'FETCH_INWARD_LIST_ERROR';
export const SET_INWARD_DETAILS = 'SET_INWARD_DETAILS';

export const FETCH_WIP_INWARD_LIST_REQUEST = 'FETCH_WIP_INWARD_LIST_REQUEST';
export const FETCH_WIP_INWARD_LIST_SUCCESS = 'FETCH_WIP_INWARD_LIST_SUCCESS';
export const FETCH_WIP_INWARD_LIST_ERROR = 'FETCH_WIP_INWARD_LIST_ERROR';

//check coil number duplicate
export const CHECK_COIL_EXISTS = 'CHECK_COIL_EXISTS';
export const CHECK_COIL_EXISTS_SUCCESS = 'CHECK_COIL_EXISTS_SUCCESS';
export const CHECK_COIL_EXISTS_ERROR = 'CHECK_COIL_EXISTS_ERROR';

export const SUBMIT_INWARD_ENTRY = 'SUBMIT_INWARD_ENTRY';
export const SUBMIT_INWARD_SUCCESS = 'SUBMIT_INWARD_SUCCESS';
export const SUBMIT_INWARD_ERROR = 'SUBMIT_INWARD_ERROR';

export const FETCH_PARTY_LIST_REQUEST = 'FETCH_PARTY_LIST_REQUEST';
export const FETCH_PARTY_LIST_SUCCESS = 'FETCH_PARTY_LIST_SUCCESS';
export const FETCH_PARTY_LIST_ERROR = 'FETCH_PARTY_LIST_ERROR';

export const FETCH_RATES_LIST_REQUEST = 'FETCH_RATES_LIST_REQUEST';
export const FETCH_RATES_LIST_SUCCESS = 'FETCH_RATES_LIST_SUCCESS';
export const FETCH_RATES_LIST_ERROR = 'FETCH_RATES_LIST_ERROR';

export const FETCH_INWARD_LIST_BY_PARTY_REQUEST = 'FETCH_INWARD_LIST_BY_PARTY_REQUEST';
export const FETCH_INWARD_LIST_BY_PARTY_SUCCESS = 'FETCH_INWARD_LIST_BY_PARTY_SUCCESS';
export const FETCH_INWARD_LIST_BY_PARTY_ERROR = 'FETCH_INWARD_LIST_BY_PARTY_ERROR';

export const FETCH_MATERIAL_LIST_REQUEST = 'FETCH_MATERIAL_LIST_REQUEST';
export const FETCH_MATERIAL_LIST_SUCCESS = 'FETCH_MATERIAL_LIST_SUCCESS';
export const FETCH_MATERIAL_LIST_ERROR = 'FETCH_MATERIAL_LIST_ERROR';

export const FETCH_MATERIAL_GRADE_LIST_REQUEST = 'FETCH_MATERIAL_GRADE_LIST_REQUEST';
export const FETCH_MATERIAL_GRADE_LIST_SUCCESS = 'FETCH_MATERIAL_GRADE_LIST_SUCCESS';
export const FETCH_MATERIAL_GRADE_LIST_ERROR = 'FETCH_MATERIAL_GRADE_LIST_ERROR';

export const FETCH_INWARD_PLAN_DETAILS_REQUESTED = 'FETCH_INWARD_PLAN_DETAILS_REQUESTED';
export const FETCH_INWARD_PLAN_DETAILS_SUCCESS = 'FETCH_INWARD_PLAN_DETAILS_SUCCESS';
export const FETCH_INWARD_PLAN_DETAILS_ERROR = 'FETCH_INWARD_PLAN_DETAILS_ERROR';

export const SET_PROCESS_DETAILS = 'SET_PROCESS_DETAILS';

export const REQUEST_SAVE_CUTTING_DETAILS = 'REQUEST_SAVE_CUTTING_DETAILS';
export const SAVE_CUTTING_DETAILS_SUCCESS = 'SAVE_CUTTING_DETAILS_SUCCESS';
export const SAVE_CUTTING_DETAILS_ERROR = 'SAVE_CUTTING_DETAILS_ERROR';

export const REQUEST_SAVE_SLITTING_DETAILS = 'REQUEST_SAVE_SLITTING_DETAILS';
export const SAVE_SLITTING_DETAILS_SUCCESS = 'SAVE_SLITTING_DETAILS_SUCCESS';
export const SAVE_SLITTING_DETAILS_ERROR = 'SAVE_SLITTING_DETAILS_ERROR';

export const REQUEST_UPDATE_INSTRUCTION_DETAILS = 'REQUEST_UPDATE_INSTRUCTION_DETAILS';
export const REQUEST_UPDATE_INSTRUCTION_DETAILS_SUCCESS = 'REQUEST_UPDATE_INSTRUCTION_DETAILS_SUCCESS';
export const REQUEST_UPDATE_INSTRUCTION_DETAILS_ERROR = 'REQUEST_UPDATE_INSTRUCTION_DETAILS_ERROR';

export const RESET_INSTRUCTION_FORM = 'RESET_INSTRUCTION_FORM';
export const RESET_INWARD_FORM = 'RESET_INWARD_FORM';
export const RESET_DELETE_INWARD = 'RESET_DELETE_INWARD';
export const REST_ISDELETED = 'REST_ISDELETED';

export const FETCH_DELIVERY_LIST_REQUEST = 'FETCH_DELIVERY_LIST_REQUEST';
export const FETCH_DELIVERY_LIST_SUCCESS = 'FETCH_DELIVERY_LIST_SUCCESS';
export const FETCH_DELIVERY_LIST_ERROR = 'FETCH_DELIVERY_LIST_ERROR';

export const FETCH_DELIVERY_LIST_REQUEST_BY_ID = 'FETCH_DELIVERY_LIST_REQUEST_BY_ID';
export const FETCH_DELIVERY_LIST_SUCCESS_BY_ID = 'FETCH_DELIVERY_LIST_SUCCESS_BY_ID';
export const FETCH_DELIVERY_LIST_ERROR_BY_ID = 'FETCH_DELIVERY_LIST_ERROR_BY_ID';

export const SET_INWARD_SELECTED_FOR_DELIVERY = 'SET_INWARD_SELECTED_FOR_DELIVERY';
export const POST_DELIVERY_CONFIRM_REQUESTED = "POST_DELIVERY_CONFIRM_REQUESTED";
export const POST_DELIVERY_CONFIRM_SUCCESS = "POST_DELIVERY_CONFIRM_SUCCESS";
export const POST_DELIVERY_CONFIRM_ERROR = "POST_DELIVERY_CONFIRM_ERROR";

export const FETCH_INWARD_INSTRUCTION_DETAILS_REQUESTED = 'FETCH_INWARD_INSTRUCTION_DETAILS_REQUESTED';
export const FETCH_INWARD_INSTRUCTION_DETAILS_SUCCESS = 'FETCH_INWARD_INSTRUCTION_DETAILS_SUCCESS';
export const FETCH_INWARD_INSTRUCTION_DETAILS_ERROR = 'FETCH_INWARD_INSTRUCTION_DETAILS_ERROR';

export const FETCH_INWARD_INSTRUCTION_WIP_DETAILS_REQUESTED = 'FETCH_INWARD_INSTRUCTION_WIP_DETAILS_REQUESTED';
export const FETCH_INWARD_INSTRUCTION_WIP_DETAILS_SUCCESS = 'FETCH_INWARD_INSTRUCTION_WIP_DETAILS_SUCCESS';
export const FETCH_INWARD_INSTRUCTION_WIP_DETAILS_ERROR = 'FETCH_INWARD_INSTRUCTION_WIP_DETAILS_ERROR';
export const SAVE_UNPROCESSED_FOR_DELIVERY = 'SAVE_UNPROCESSED_FOR_DELIVERY';
export const SAVE_UNPROCESSED_FOR_DELIVERY_SUCCESS = 'SAVE_UNPROCESSED_FOR_DELIVERY_SUCCESS';
export const SAVE_UNPROCESSED_FOR_DELIVERY_ERROR = 'SAVE_UNPROCESSED_FOR_DELIVERY_ERROR';
export const FETCH_INWARD_LIST_BY_ID = 'FETCH_INWARD_LIST_BY_ID';
export const FETCH_INWARD_LIST_BY_ID_SUCCESS = 'FETCH_INWARD_LIST_BY_ID_SUCCESS';
export const FETCH_INWARD_LIST_BY_ID_ERROR = 'FETCH_INWARD_LIST_BY_ID_ERROR';
export const UPDATE_INWARD_LIST = 'UPDATE_INWARD_LIST';
export const UPDATE_INWARD_LIST_ERROR = 'UPDATE_INWARD_LIST_ERROR';
export const UPDATE_INWARD_LIST_SUCCESS = 'UPDATE_INWARD_LIST_SUCCESS';
export const DELETE_INWARD_LIST_BY_ID = 'DELETE_INWARD_LIST_BY_ID';
export const DELETE_INWARD_LIST_BY_ID_ERROR = 'DELETE_INWARD_LIST_BY_ID_ERROR';
export const DELETE_INWARD_LIST_BY_ID_SUCCESS = 'DELETE_INWARD_LIST_BY_ID_SUCCESS';

export const FETCH_CLASSIFICATION_LIST_REQUEST= 'FETCH_CLASSIFICATION_LIST_REQUEST';
export const FETCH_CLASSIFICATION_LIST_SUCCESS= 'FETCH_CLASSIFICATION_LIST_SUCCESS';
export const FETCH_CLASSIFICATION_LIST_ERROR= 'FETCH_CLASSIFICATION_LIST_ERROR';

export const DELETE_INSTRUCTION_BY_ID = 'DELETE_INSTRUCTION_BY_ID';
export const DELETE_INSTRUCTION_BY_ID_ERROR = 'DELETE_INSTRUCTION_BY_ID_ERROR';
export const DELETE_INSTRUCTION_BY_ID_SUCCESS = 'DELETE_INSTRUCTION_BY_ID_SUCCESS';
export const DELETE_INSTRUCTION_BY_ID_SUCCESS_SLIT = 'DELETE_INSTRUCTION_BY_ID_SUCCESS_SLIT';
export const CHECK_BATCH_NO_EXIST = 'CHECK_BATCH_NO_EXIST';
export const CHECK_BATCH_NO_EXIST_SUCCESS = 'CHECK_BATCH_NO_EXIST_SUCCESS';
export const CHECK_BATCH_NO_EXIST_ERROR = 'CHECK_BATCH_NO_EXIST_ERROR';
export const INSTRUCTION_GROUP_SAVE = 'INSTRUCTION_GROUP_SAVE';
export const INSTRUCTION_GROUP_SAVE_SUCCESS = 'INSTRUCTION_GROUP_SAVE_SUCCESS';
export const INSTRUCTION_GROUP_SAVE_ERROR = 'INSTRUCTION_GROUP_SAVE_ERROR';

export const ADD_MATERIAL_REQUEST= 'ADD_MATERIAL_REQUEST';
export const ADD_MATERIAL_SUCCESS= 'ADD_MATERIAL_SUCCESS';
export const ADD_MATERIAL_ERROR= 'ADD_MATERIAL_ERROR';

export const ADD_PARTY_REQUEST= 'ADD_PARTY_REQUEST';
export const ADD_PARTY_SUCCESS= 'ADD_PARTY_SUCCESS';
export const ADD_PARTY_ERROR= 'ADD_PARTY_ERROR';

export const ADD_RATES_REQUEST= 'ADD_RATES_REQUEST';
export const ADD_RATES_SUCCESS= 'ADD_RATES_SUCCESS';
export const ADD_RATES_ERROR= 'ADD_RATES_ERROR';

export const ADD_PACKING_RATES_REQUEST= 'ADD_PACKING_RATES_REQUEST';
export const ADD_PACKING_RATES_SUCCESS= 'ADD_PACKING_RATES_SUCCESS';
export const ADD_PACKING_RATES_ERROR= 'ADD_PACKING_RATES_ERROR';

export const UPDATE_MATERIAL_REQUEST= 'UPDATE_MATERIAL_REQUEST';
export const UPDATE_MATERIAL_SUCCESS= 'UPDATE_MATERIAL_SUCCESS';
export const UPDATE_MATERIAL_ERROR= 'UPDATE_MATERIAL_ERROR';

export const UPDATE_RATES_REQUEST= 'UPDATE_RATES_REQUEST';
export const UPDATE_RATES_SUCCESS= 'UPDATE_RATES_SUCCESS';
export const UPDATE_RATES_ERROR= 'UPDATE_RATES_ERROR';

export const UPDATE_PACKING_RATES_REQUEST= 'UPDATE_PACKING_RATES_REQUEST';
export const UPDATE_PACKING_RATES_SUCCESS= 'UPDATE_PACKING_RATES_SUCCESS';
export const UPDATE_PACKING_RATES_ERROR= 'UPDATE_PACKING_RATES_ERROR';

export const UPDATE_PARTY_REQUEST= 'UPDATE_PARTY_REQUEST';
export const UPDATE_PARTY_SUCCESS= 'UPDATE_PARTY_SUCCESS';
export const UPDATE_PARTY_ERROR= 'UPDATE_PARTY_ERROR';

export const FETCH_MATERIAL_LIST_ID_REQUEST= 'FETCH_MATERIAL_LIST_ID_REQUEST';
export const FETCH_MATERIAL_LIST_ID_SUCCESS= 'FETCH_MATERIAL_LIST_ID_SUCCESS';
export const FETCH_MATERIAL_LIST_ID_ERROR= 'FETCH_MATERIAL_LIST_ID_ERROR';

export const FETCH_PACKING_LIST_REQUEST = 'FETCH_PACKING_LIST_REQUEST';
export const FETCH_PACKING_LIST_SUCCESS = 'FETCH_PACKING_LIST_SUCCESS';
export const FETCH_PACKING_LIST_ERROR = 'FETCH_PACKING_LIST_ERROR';

export const FETCH_PACKING_LIST_BY_PARTY_REQUEST = 'FETCH_PACKING_LIST_BY_PARTY_REQUEST';
export const FETCH_PACKING_LIST_BY_PARTY_SUCCESS = 'FETCH_PACKING_LIST_BY_PARTY_SUCCESS';
export const FETCH_PACKING_LIST_BY_PARTY_ERROR = 'FETCH_PACKING_LIST_BY_PARTY_ERROR';

export const FETCH_PACKING_RATES_LIST_REQUEST = 'FETCH_PACKING_RATES_LIST_REQUEST';
export const FETCH_PACKING_RATES_LIST_SUCCESS = 'FETCH_PACKING_RATES_LIST_SUCCESS';
export const FETCH_PACKING_RATES_LIST_ERROR = 'FETCH_PACKING_RATES_LIST_ERROR';

export const FETCH_PACKING_BUCKET_LIST_REQUEST = 'FETCH_PACKING_BUCKET_LIST_REQUEST';
export const FETCH_PACKING_BUCKET_LIST_SUCCESS = 'FETCH_PACKING_BUCKET_LIST_SUCCESS';
export const FETCH_PACKING_BUCKET_LIST_ERROR = 'FETCH_PACKING_BUCKET_LIST_ERROR';

export const ADD_PACKING_REQUEST = 'ADD_PACKING_REQUEST';
export const ADD_PACKING_SUCCESS = 'ADD_PACKING_SUCCESS';
export const ADD_PACKING_ERROR = 'ADD_PACKING_ERROR';

export const ADD_PACKING_BUCKET_REQUEST = 'ADD_PACKING_BUCKET_REQUEST';
export const ADD_PACKING_BUCKET_SUCCESS = 'ADD_PACKING_BUCKET_SUCCESS';
export const ADD_PACKING_BUCKET_ERROR = 'ADD_PACKING_BUCKET_ERROR';

export const FETCH_PACKING_LIST_ID_REQUEST = 'FETCH_PACKING_LIST_ID_REQUEST';
export const FETCH_PACKING_LIST_ID_SUCCESS = 'FETCH_PACKING_LIST_ID_SUCCESS';
export const FETCH_PACKING_LIST_ID_ERROR = 'FETCH_PACKING_LIST_ID_ERROR';

export const FETCH_PACKING_BUCKET_LIST_ID_REQUEST = 'FETCH_PACKING_BUCKET_LIST_ID_REQUEST';
export const FETCH_PACKING_BUCKET_LIST_ID_SUCCESS = 'FETCH_PACKING_BUCKET_LIST_ID_SUCCESS';
export const FETCH_PACKING_BUCKET_LIST_ID_ERROR = 'FETCH_PACKING_BUCKET_LIST_ID_ERROR';

export const UPDATE_PACKING_REQUEST = 'UPDATE_PACKING_REQUEST';
export const UPDATE_PACKING_SUCCESS = 'UPDATE_PACKING_SUCCESS';
export const UPDATE_PACKING_ERROR = 'UPDATE_PACKING_ERROR';

export const UPDATE_PACKING_BUCKET_REQUEST = 'UPDATE_PACKING_BUCKET_REQUEST';
export const UPDATE_PACKING_BUCKET_SUCCESS = 'UPDATE_PACKING_BUCKET_SUCCESS';
export const UPDATE_PACKING_BUCKET_ERROR = 'UPDATE_PACKING_BUCKET_ERROR';

export const RESET_PACKING_REQUEST = 'RESET_PACKING_REQUEST';
export const RESET_PACKING_BUCKET_REQUEST = 'RESET_PACKING_BUCKET_REQUEST';

export const FETCH_PROCESS_LIST_REQUEST= 'FETCH_PROCESS_LIST_REQUEST';
export const FETCH_PROCESS_LIST_SUCCESS= 'FETCH_PROCESS_LIST_SUCCESS';
export const FETCH_PROCESS_LIST_ERROR= 'FETCH_PROCESS_LIST_ERROR';

export const FETCH_RATES_LIST_ID_REQUEST= 'FETCH_RATES_LIST_ID_REQUEST';
export const FETCH_RATES_LIST_ID_SUCCESS= 'FETCH_RATES_LIST_ID_SUCCESS';
export const FETCH_RATES_LIST_ID_ERROR= 'FETCH_RATES_LIST_ID_ERROR';

export const FETCH_PACKING_RATES_LIST_ID_REQUEST= 'FETCH_PACKING_RATES_LIST_ID_REQUEST';
export const FETCH_PACKING_RATES_LIST_ID_SUCCESS= 'FETCH_PACKING_RATES_LIST_ID_SUCCESS';
export const FETCH_PACKING_RATES_LIST_ID_ERROR= 'FETCH_PACKING_RATES_LIST_ID_ERROR';

export const FETCH_PARTY_LIST_ID_ERROR= 'FETCH_PARTY_LIST_ID_ERROR';
export const FETCH_PARTY_LIST_ID_REQUEST= 'FETCH_PARTY_LIST_ID_REQUEST';
export const FETCH_PARTY_LIST_ID_SUCCESS= 'FETCH_PARTY_LIST_ID_SUCCESS';

export const RESET_MATERIAL_REQUEST= 'RESET_MATERIAL_REQUEST';
export const RESET_PARTY_REQUEST= 'RESET_PARTY_REQUEST';
export const RESET_RATES_REQUEST= 'RESET_RATES_REQUEST';
export const RESET_PACKING_RATES_REQUEST = 'RESET_PACKING_RATES_REQUEST';

export const PDF_GENERATE_INWARD= 'PDF_GENERATE_INWARD';
export const PDF_GENERATE_INWARD_ERROR= 'PDF_GENERATE_INWARD_ERROR';
export const PDF_GENERATE_INWARD_SUCCESS= 'PDF_GENERATE_INWARD_SUCCESS';

export const PDF_GENERATE_DELIVERY= 'PDF_GENERATE_DELIVERY';
export const PDF_GENERATE_DELIVERY_ERROR= 'PDF_GENERATE_DELIVERY_ERROR';
export const PDF_GENERATE_DELIVERY_SUCCESS= 'PDF_GENERATE_DELIVERY_SUCCESS';

export const DELETE_DELIVERY_BY_ID= 'DELETE_DELIVERY_BY_ID';
export const DELETE_DELIVERY_BY_ID_ERROR= 'DELETE_DELIVERY_BY_ID_ERROR';
export const DELETE_DELIVERY_BY_ID_SUCCESS= 'DELETE_DELIVERY_BY_IDSUCCESS';

export const SEND_REPORT_REQUEST='SEND_REPORT_REQUEST';
export const SEND_REPORT_SUCCESS='SEND_REPORT_SUCCESS';
export const SEND_REPORT_ERROR='SEND_REPORT_ERROR';
export const RESET_REPORT_SUCCESS='RESET_REPORT_SUCCESS';


export const ADD_CLASSIFICATIONLIST_REQUEST= 'ADD_CLASSIFICATIONLIST_REQUEST';
export const ADD_CLASSIFICATIONLIST_SUCCESS = 'ADD_CLASSIFICATIONLIST_SUCCESS';
export const ADD_CLASSIFICATIONLIST_ERROR = 'ADD_CLASSIFICATIONLIST_ERROR';



export const ADD_PROCESSTAGS_REQUEST= 'ADD_PROCESSTAGS_REQUEST';
export const ADD_PROCESSTAGS_SUCCESS = 'ADD_PROCESSTAGS_SUCCESS';
export const ADD_PROCESSTAGS_ERROR = 'ADD_PROCESSTAGS_ERROR';

export const ADD_ENDUSERTAGS_REQUEST= 'ADD_ENDUSERTAGS_REQUEST';
export const ADD_ENDUSERTAGS_SUCCESS = 'ADD_ENDUSERTAGS_SUCCESS';
export const ADD_ENDUSERTAGS_ERROR = 'ADD_ENDUSERTAGS_ERROR';

export const FETCH_TAGS_LIST_BY_ID_ERROR= 'FETCH_TAGS_LIST_BY_ID_ERROR';
export const FETCH_TAGS_LIST_BY_ID_REQUEST= 'FETCH_TAGS_LIST_BY_ID_REQUEST';
export const FETCH_TAGS_LIST_BY_ID_SUCCESS= 'FETCH_TAGS_LIST_BY_ID_SUCCESS';

export const FETCH_ENDUSERTAGS_LIST_REQUEST= 'FETCH_ENDUSERTAGS_LIST_REQUEST';
export const FETCH_ENDUSERTAGS_LIST_SUCCESS= 'FETCH_ENDUSERTAGS_LIST_SUCCESS';
export const FETCH_ENDUSERTAGS_LIST_ERROR= 'FETCH_ENDUSERTAGS_LIST_ERROR';


export const DELETE_TAGS_BY_ID_ERROR= 'DELETE_TAGS_BY_ID_ERROR';
export const DELETE_TAGS_BY_ID_REQUEST= 'DELETE_TAGS_BY_ID_REQUEST';
export const DELETE_TAGS_BY_ID_SUCCESS= 'DELETE_TAGS_BY_ID_SUCCESS';
export const RESET_TAGS_STATE= 'RESET_TAGS_STATE';

export const UPDATE_TAGS_REQUEST= 'UPDATE_TAGS_REQUEST';
export const UPDATE_TAGS_SUCCESS= 'UPDATE_TAGS_SUCCESS';
export const UPDATE_TAGS_ERROR= 'UPDATE_TAGS_ERROR';

export const DELETE_RATES_BY_ID_ERROR= 'DELETE_RATES_BY_ID_ERROR';
export const DELETE_RATES_BY_ID= 'DELETE_RATES_BY_ID';
export const DELETE_RATES_BY_ID_SUCCESS= 'DELETE_RATES_BY_ID_SUCCESS';

export const DELETE_ADDITIONAL_RATES_BY_ID_ERROR= 'DELETE_ADDITIONAL_RATES_BY_ID_ERROR';
export const DELETE_ADDITIONAL_RATES_BY_ID= 'DELETE_ADDITIONAL_RATES_BY_ID';
export const DELETE_ADDITIONAL_RATES_BY_ID_SUCCESS= 'DELETE_ADDITIONAL_RATES_BY_ID_SUCCESS';

export const ADD_ADDITIONAL_RATES_REQUEST= 'ADD_ADDITIONAL_RATES_REQUEST';
export const ADD_ADDITIONAL_RATES_SUCCESS= 'ADD_ADDITIONAL_RATES_SUCCESS';
export const ADD_ADDITIONAL_RATES_ERROR= 'ADD_ADDITIONAL_RATES_ERROR';

export const FETCH_STATIC_LIST_BY_PROCESSS_ERROR= 'FETCH_STATIC_LIST_BY_PROCESSS_ERROR';
export const FETCH_STATIC_LIST_BY_PROCESSS= 'FETCH_STATIC_LIST_BY_PROCESSS';
export const FETCH_STATIC_LIST_BY_PROCESSS_SUCCESS= 'FETCH_STATIC_LIST_BY_PROCESSS_SUCCESS';
export const FETCH_ADDITIONAL_RATES_LIST_REQUEST_ERROR= 'FETCH_ADDITIONAL_RATES_LIST_REQUEST_ERROR';
export const FETCH_ADDITIONAL_RATES_LIST_REQUEST= 'FETCH_ADDITIONAL_RATES_LIST_REQUEST';
export const FETCH_ADDITIONAL_RATES_LIST_REQUEST_SUCCESS= 'FETCH_ADDITIONAL_RATES_LIST_REQUEST_SUCCESS';

export const UPDATE_ADDITIONAL_RATES_REQUEST= 'UPDATE_ADDITIONAL_RATES_REQUEST';
export const UPDATE_ADDITIONAL_RATES_SUCCESS= 'UPDATE_ADDITIONAL_RATES_SUCCESS';
export const UPDATE_ADDITIONAL_RATES_ERROR= 'UPDATE_ADDITIONAL_RATES_ERROR';

export const FETCH_ADDITIONAL_RATES_LIST_BY_ID_REQUEST_ERROR= 'FETCH_ADDITIONAL_RATES_LIST_BY_ID_REQUEST_ERROR';
export const FETCH_ADDITIONAL_RATES_LIST_BY_ID_REQUEST= 'FETCH_ADDITIONAL_RATES_LIST_BY_ID_REQUEST';
export const FETCH_ADDITIONAL_RATES_LIST_BY_ID_REQUEST_SUCCESS= 'FETCH_ADDITIONAL_RATES_LIST_BY_ID_REQUEST_SUCCESS';

export const PDF_S3_URL= 'PDF_S3_URL';
export const PDF_S3_URL_ERROR= 'PDF_S3_URL_ERROR';
export const PDF_S3_URL_SUCCESS= 'PDF_S3_URL_SUCCESS';

export const GET_RECONCILE_REPORT_ERROR= 'GET_RECONCILE_REPORT_ERROR';
export const GET_RECONCILE_REPORT_SUCCESS='GET_RECONCILE_REPORT_SUCCESS';
export const GET_RECONCILE_REPORT='GET_RECONCILE_REPORT'
export const FETCH_TEMPLATE_LIST='FETCH_TEMPLATE_LIST'
export const SAVE_TEMPLATE_REQUEST='SAVE_TEMPLATE_REQUEST'
export const CREATE_FORM_FIELDS='CREATE_FORM_FIELDS'
export const SAVE_TEMPLATE_SUCCESS='SAVE_TEMPLATE_SUCCESS'
export const SAVE_TEMPLATE_ERROR='SAVE_TEMPLATE_ERROR'
export const FETCH_TEMPLATE_LIST_SUCCESS='FETCH_TEMPLATE_LIST_SUCCESS'
export const FETCH_TEMPLATE_LIST_ERROR='FETCH_TEMPLATE_LIST_ERROR'
export const TEMPLATE_NAME='TEMPLATE_NAME'
export const SAVE_QUALITY_TEMPLATE_REQUEST='SAVE_QUALITY_TEMPLATE_REQUEST'
export const SAVE_QUALITY_TEMPLATE_SUCCESS='SAVE_QUALITY_TEMPLATE_SUCCESS'
export const SAVE_QUALITY_TEMPLATE_ERROR='SAVE_QUALITY_TEMPLATE_ERROR'
export const GET_QUALITY_TEMPLATE_BY_ID_REQUEST='GET_QUALITY_TEMPLATE_BY_ID_REQUEST'
export const GET_QUALITY_TEMPLATE_BY_ID_SUCCESS='GET_QUALITY_TEMPLATE_BY_ID_SUCCESS'
export const GET_QUALITY_TEMPLATE_BY_ID_ERROR='GET_QUALITY_TEMPLATE_BY_ID_ERROR'
export const UPDATE_QUALITY_TEMPLATE_REQUEST='UPDATE_QUALITY_TEMPLATE_REQUEST'
export const UPDATE_QUALITY_TEMPLATE_SUCCESS='UPDATE_QUALITY_TEMPLATE_SUCCESS'
export const UPDATE_QUALITY_TEMPLATE_ERROR='UPDATE_QUALITY_TEMPLATE_ERROR'
export const DELETE_QUALITY_TEMPLATE_REQUEST='DELETE_QUALITY_TEMPLATE_REQUEST'
export const DELETE_QUALITY_TEMPLATE_SUCCESS='DELETE_QUALITY_TEMPLATE_SUCCESS'
export const DELETE_QUALITY_TEMPLATE_ERROR='DELETE_QUALITY_TEMPLATE_ERROR'
export const FETCH_TEMPLATE_LINK_LIST='FETCH_TEMPLATE_LINK_LIST'
export const FETCH_TEMPLATE_LINK_LIST_SUCCESS='FETCH_TEMPLATE_LINK_LIST_SUCCESS'
export const FETCH_TEMPLATE_LINK_LIST_ERROR='FETCH_TEMPLATE_LINK_LIST_ERROR'
export const SAVE_QUALITY_TEMPLATE_LINK_REQUEST='SAVE_QUALITY_TEMPLATE_LINK_REQUEST'
export const SAVE_QUALITY_TEMPLATE_LINK_SUCCESS='SAVE_QUALITY_TEMPLATE_LINK_SUCCESS'
export const SAVE_QUALITY_TEMPLATE_LINK_ERROR='SAVE_QUALITY_TEMPLATE_LINK_ERROR'
export const GET_QUALITY_TEMPLATE_LINK_BY_ID_REQUEST='GET_QUALITY_TEMPLATE_LINK_BY_ID_REQUEST'
export const GET_QUALITY_TEMPLATE_LINK_BY_ID_SUCCESS='GET_QUALITY_TEMPLATE_LINK_BY_ID_SUCCESS'
export const GET_QUALITY_TEMPLATE_LINK_BY_ID_ERROR='GET_QUALITY_TEMPLATE_LINK_BY_ID_ERROR'
export const UPDATE_QUALITY_TEMPLATE_LINK_REQUEST='UPDATE_QUALITY_TEMPLATE_LINK_REQUEST'
export const UPDATE_QUALITY_TEMPLATE_LINK_SUCCESS='UPDATE_QUALITY_TEMPLATE_LINK_SUCCESS'
export const UPDATE_QUALITY_TEMPLATE_LINK_ERROR='UPDATE_QUALITY_TEMPLATE_LINK_ERROR'
export const DELETE_QUALITY_TEMPLATE_LINK_REQUEST='DELETE_QUALITY_TEMPLATE_LINK_REQUEST'
export const DELETE_QUALITY_TEMPLATE_LINK_SUCCESS='DELETE_QUALITY_TEMPLATE_LINK_SUCCESS'
export const DELETE_QUALITY_TEMPLATE_LINK_ERROR='DELETE_QUALITY_TEMPLATE_LINK_ERROR'
//kqp 
export const FETCH_KQP_LIST='FETCH_KQP_LIST'
export const FETCH_KQP_LIST_SUCCESS='FETCH_KQP_LIST_SUCCESS'
export const FETCH_KQP_LIST_ERROR='FETCH_KQP_LIST_ERROR'
export const SAVE_KQP_REQUEST='SAVE_KQP_REQUEST'
export const SAVE_KQP_SUCCESS='SAVE_KQP_SUCCESS'
export const SAVE_KQP_ERROR='SAVE_KQP_ERROR'
export const GET_KQP_BY_ID_REQUEST='GET_KQP_BY_ID_REQUEST'
export const GET_KQP_BY_ID_SUCCESS='GET_KQP_BY_ID_SUCCESS'
export const GET_KQP_BY_ID_ERROR='GET_KQP_BY_ID_ERROR'
export const UPDATE_KQP_REQUEST='UPDATE_KQP_REQUEST'
export const UPDATE_KQP_SUCCESS='UPDATE_KQP_SUCCESS'
export const UPDATE_KQP_ERROR='UPDATE_KQP_ERROR'
export const DELETE_KQP_REQUEST='DELETE_KQP_REQUEST'
export const DELETE_KQP_SUCCESS='DELETE_KQP_SUCCESS'
export const DELETE_KQP_ERROR='DELETE_KQP_ERROR'
//kqp link
export const FETCH_KQP_LINK_LIST='FETCH_KQP_LINK_LIST'
export const FETCH_KQP_LINK_LIST_SUCCESS='FETCH_KQP_LINK_LIST_SUCCESS'
export const FETCH_KQP_LINK_LIST_ERROR='FETCH_KQP_LINK_LIST_ERROR'
export const SAVE_KQP_LINK_REQUEST='SAVE_KQP_LINK_REQUEST'
export const SAVE_KQP_LINK_SUCCESS='SAVE_KQP_LINK_SUCCESS'
export const SAVE_KQP_LINK_ERROR='SAVE_KQP_LINK_ERROR'
export const GET_KQP_LINK_BY_ID_REQUEST='GET_KQP_LINK_BY_ID_REQUEST'
export const GET_KQP_LINK_BY_ID_SUCCESS='GET_KQP_LINK_BY_ID_SUCCESS'
export const GET_KQP_LINK_BY_ID_ERROR='GET_KQP_LINK_BY_ID_ERROR'
export const UPDATE_KQP_LINK_REQUEST='UPDATE_LINK_KQP_REQUEST'
export const UPDATE_KQP_LINK_SUCCESS='UPDATE_LINK_KQP_SUCCESS'
export const UPDATE_KQP_LINK_ERROR='UPDATE_KQP_LINK_ERROR'
export const DELETE_KQP_LINK_REQUEST='DELETE_KQP_LINK_REQUEST'
export const DELETE_KQP_LINK_SUCCESS='DELETE_KQP_LINK_SUCCESS'
export const DELETE_KQP_LINK_ERROR='DELETE_KQP_LINK_ERROR'
//quality report
export const  FETCH_QUALITY_REPORT_STAGE_REQUEST = "FETCH_QUALITY_REPORT_STAGE_REQUEST"
export const  FETCH_QUALITY_REPORT_STAGE_SUCCESS = "FETCH_QUALITY_REPORT_STAGE_SUCCESS"
export const  FETCH_QUALITY_REPORT_STAGE_ERROR = "FETCH_QUALITY_REPORT_STAGE_ERROR"
export const  FETCH_QUALITY_REPORT_REQUEST = "FETCH_QUALITY_REPORT_REQUEST"
export const  FETCH_QUALITY_REPORT_SUCCESS = "FETCH_QUALITY_REPORT_SUCCESS"
export const  FETCH_QUALITY_REPORT_ERROR = "FETCH_QUALITY_REPORT_ERROR"
export const SAVE_QUALITY_REPORT_REQUEST='SAVE_QUALITY_REPORT_REQUEST'
export const SAVE_QUALITY_REPORT_SUCCESS='SAVE_QUALITY_REPORT_SUCCESS'
export const SAVE_QUALITY_REPORT_ERROR='SAVE_QUALITY_REPORT_ERROR'
export const GET_QUALITY_REPORT_BY_ID_REQUEST='GET_QUALITY_REPORT_BY_ID_REQUEST'
export const GET_QUALITY_REPORT_BY_ID_SUCCESS='GET_QUALITY_REPORT_BY_ID_SUCCESS'
export const GET_QUALITY_REPORT_BY_ID_ERROR='GET_QUALITY_REPORT_BY_ID_ERROR'
export const UPDATE_QUALITY_REPORT_REQUEST='UPDATE_QUALITY_REPORT_REQUEST'
export const UPDATE_QUALITY_REPORT_SUCCESS='UPDATE_QUALITY_REPORT_SUCCESS'
export const UPDATE_QUALITY_REPORT_ERROR='UPDATE_QUALITY_REPORT_ERROR'
export const DELETE_QUALITY_REPORT_REQUEST='DELETE_QUALITY_REPORT_REQUEST'
export const DELETE_QUALITY_REPORT_SUCCESS='DELETE_QUALITY_REPORT_SUCCESS'
export const DELETE_QUALITY_REPORT_ERROR='DELETE_QUALITY_REPORT_ERROR'
export const UPDATE_QR_PROCESSING_FORM_DATA='UPDATE_QR_PROCESSING_FORM_DATA'

// template
export const FETCH_MATERIAL_GRADES='FETCH_MATERIAL_GRADES'
export const FETCH_MATERIAL_GRADES_SUCCESS='FETCH_MATERIAL_GRADES_SUCCESS'
export const FETCH_MATERIAL_GRADES_ERROR='FETCH_MATERIAL_GRADES_ERROR'
export const FETCH_WIDTHS='FETCH_WIDTHS'
export const FETCH_WIDTHS_SUCCESS='FETCH_WIDTHS_SUCCESS'
export const FETCH_WIDTHS_ERROR='FETCH_WIDTHS_ERROR'
export const FETCH_LENGTHS='FETCH_LENGTHS'
export const FETCH_LENGTHS_SUCCESS='FETCH_LENGTHS_SUCCESS'
export const FETCH_LENGTHS_ERROR='FETCH_LENGTHS_ERROR'
export const FETCH_THICKNESS='FETCH_THICKNESS'
export const FETCH_THICKNESS_SUCCESS='FETCH_THICKNESS_SUCCESS'
export const FETCH_THICKNESS_ERROR='FETCH_THICKNESS_ERROR'
export const UPDATE_TEMPLATE_PROCESSING_FORM_DATA='UPDATE_TEMPLATE_PROCESSING_FORM_DATA'
//generate QR code plan
export const QR_Code_GENERATE_PLAN= 'QR_Code_GENERATE_PLAN';
export const QR_Code_GENERATE_PLAN_ERROR= 'QR_Code_GENERATE_PLAN_ERROR';
export const QR_Code_GENERATE_PLAN_SUCCESS= 'QR_Code_GENERATE_PLAN_SUCCESS';
export const GET_PACKET_WISE_PRICE_DC_REQUEST='GET_PACKET_WISE_PRICE_DC_REQUEST'
export const GET_PACKET_WISE_PRICE_DC_SUCCESS='GET_PACKET_WISE_PRICE_DC_SUCCESS'
export const GET_PACKET_WISE_PRICE_DC_ERROR='GET_PACKET_WISE_PRICE_DC_ERROR'
