export const CUTTING_INSTRUCTION_PROCESS_ID = 1;
export const SLITTING_INSTRUCTION_PROCESS_ID = 2;
export const SLIT_CUT_INSTRUCTION_PROCESS_ID = 3;

export const APPLICATION_DATE_FORMAT = 'DD/MM/YYYY'