name: Deploy React App

on:
  push:
    branches:
      - major-ui   #change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        
      - name: Install dependencies
        run: yarn install

      - name: Build React app
        run: yarn build2
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          CI: false

      - name: Copy build folder to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_USER_PROD }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/*"
          target: "/usr/share/nginx/html"   # path in nginx config

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_HOST_PROD }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
